const FETCH_PROGRESS = 'ui/FETCH_PROGRESS' as const;
const FETCH_SUCCEED = 'ui/FETCH_SUCCEED' as const;
const FETCH_FAILED = 'ui/FETCH_FAILED' as const;
const FEEDBACK_MESSAGE_CLOSED = 'ui/FEEDBACK_MESSAGE_CLOSED' as const;

export { FETCH_PROGRESS, FETCH_SUCCEED, FETCH_FAILED, FEEDBACK_MESSAGE_CLOSED };
